<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chat Export - {{ $influencer->name }}</title>
    <style>
        body {
            font-family: 'DejaVu Sans', Arial, sans-serif;
            margin: 20px;
            color: #333;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #4a90e2;
            padding-bottom: 15px;
            margin-bottom: 30px;
        }
        .header h1 {
            color: #4a90e2;
            margin: 0 0 10px 0;
            font-size: 24px;
        }
        .header .subtitle {
            color: #666;
            font-size: 12px;
        }
        .chat-message {
            margin-bottom: 20px;
            page-break-inside: avoid;
        }
        .user-message {
            background-color: #e3f2fd;
            padding: 10px;
            border-radius: 8px;
            margin-bottom: 5px;
        }
        .influencer-message {
            background-color: #f5f5f5;
            padding: 10px;
            border-radius: 8px;
            margin-bottom: 5px;
        }
        .message-label {
            font-weight: bold;
            color: #4a90e2;
            font-size: 12px;
            margin-bottom: 5px;
        }
        .influencer-label {
            font-weight: bold;
            color: #666;
            font-size: 12px;
            margin-bottom: 5px;
        }
        .message-text {
            font-size: 14px;
            line-height: 1.6;
            margin: 5px 0;
        }
        .timestamp {
            font-size: 10px;
            color: #999;
            margin-top: 5px;
        }
        .footer {
            text-align: center;
            margin-top: 30px;
            padding-top: 15px;
            border-top: 1px solid #ddd;
            font-size: 10px;
            color: #999;
        }
        .chat-divider {
            border-bottom: 1px dashed #ddd;
            margin: 15px 0;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Chat Conversation</h1>
        <div class="subtitle">
            <strong>With:</strong> {{ $influencer->name }}<br>
            <strong>Session ID:</strong> {{ $sessionId }}<br>
            <strong>Exported:</strong> {{ $exportDate }}<br>
            <strong>Total Messages:</strong> {{ count($chatHistory) }}
        </div>
    </div>

    @foreach($chatHistory as $index => $chat)
        <div class="chat-message">
            <div class="user-message">
                <div class="message-label">You:</div>
                <div class="message-text">{{ $chat->message }}</div>
            </div>

            <div class="influencer-message">
                <div class="influencer-label">{{ $influencer->name }}:</div>
                <div class="message-text">{{ $chat->response }}</div>
                @if($chat->language && $chat->language !== 'en')
                    <div class="timestamp">Language: {{ strtoupper($chat->language) }} | {{ $chat->created_at->format('M d, Y H:i') }}</div>
                @else
                    <div class="timestamp">{{ $chat->created_at->format('M d, Y H:i') }}</div>
                @endif
            </div>
        </div>

        @if($index < count($chatHistory) - 1)
            <div class="chat-divider"></div>
        @endif
    @endforeach

    <div class="footer">
        Generated by Easylearningbd AI Platform -  <br>
        This is a private conversation export. Please keep it confidential.
    </div>
</body>
</html>
